### ISSUE TITLE
Assignment of colors to buildings and upgrades not working correctly

### ISSUE THREAD

**Issue by KingEliTheBoss** [CookieMonsterTeam/CookieMonster#802]
I'm very late game using Firefox 88.0.1 and there are issues with the colors based on PP not displaying correctly.

First, even tho the next upgrade in line has the lowest PP out of all the buildings it still has the color yellow instead of blue.
Second, the buildings are not showing the colors green and red for the lowest and highest PP, there are just yellow and orange.
Third, when choosing to sort the buildings by PP of x1 purchase, it doesn't do that, it jumps back and fort between values of PP.

Note how in the screenshots the upgrade has a much lower PP than the buildings yet it still is yellow. Also note how the first building has a higher PP yet is displayed first on the list

![Sin título](https://user-images.githubusercontent.com/34291912/117333064-2a040f00-ae5e-11eb-83d1-08119572a160.png)
![Sin título2](https://user-images.githubusercontent.com/34291912/117333323-6e8faa80-ae5e-11eb-831f-9df058e630d3.png)
![Sin título3](https://user-images.githubusercontent.com/34291912/117333471-93841d80-ae5e-11eb-9b49-ec288dce9d07.png)

Save file
[KingEliBakery(156).txt](https://github.com/CookieMonsterTeam/CookieMonster/files/6436232/KingEliBakery.156.txt)

**Comment by DanielNoord** [comment]
I have checked your save and I think most of it has to do with your best option being to buy 10 Idleverses.
You will see that that option is marked green. When you turn on sorting on "PP of selected bulk mode" you will see that the Idleverse will also be on top when you select the buy 10 column.
In the buy 10 column you will also find some red buildings.

This is all due to the fact that Cookie Monster compares PP values across all columns to give you a better indication of what to buy next. In #773 some solutions to making this clearer have been discussed and I intend to provide some additional indications in the next version.

I think this should solve all the problems you mention, but let me know if anything is still unclear/broken.

**Comment by KingEliTheBoss** [comment]
I think I undestand now, thanks for your quick reply
