### ISSUE TITLE
Options page keeps scrolling back to the top

### ISSUE THREAD

**Issue by ChallengerCode** [CookieMonsterTeam/CookieMonster#918]
The options page keeps scrolling back to the top, at a seemingly fixed interval of every 5 seconds the options page gets scrolled back to the top. Seems to coincide with the stats page updating which happens every 5 seconds.

Happens with existing and new save, across Firefox, Edge and Opera.

**Comment by DanielNoord** [comment]
I don't seem to be able to reproduce this on my system.

Can you share your save? Perhaps it is due to a setting I have turned off.
Do you have any other mods running?

**Comment by ChallengerCode** [comment]
Sample Savegame, didn't touch any settings at all and it happens.

`Mi4wMzF8fDE2MjczMDM4NDAwNDg7MTYyNzMwMzg0MDA0ODsxNjI3MzAzOTU2NjQwO0RhbmNpbmcgVGVhcG90O3dtdWNwfDExMTExMTAxMTAwMTAwMTAwMTAxMHwyMS44MzY2NjY2NjY2NjgwNDg7MzYuODM2NjY2NjY2NjYyODk7Mjg7MDsyODswOzA7MDswOzA7MDswOzA7MDswOzA7MDswOzA7MDswOzA7OzA7MDswOzA7MDswOzA7LTE7LTE7LTE7LTE7LTE7MDswOzA7MDs1MDswOzA7LTE7LTE7MTYyNzMwMzg0MDA0ODswOzA7OzQxOzA7MDswLjE7fDEsMSw4LDAsLDAsMTswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwO3wxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHx8Q29va2llTW9uc3Rlcjp7InNldHRpbmdzIjp7IkNQU01vZGUiOjEsIkF2Z0NQU0hpc3QiOjMsIkF2Z0NsaWNrc0hpc3QiOjAsIkNhbGNXcmluayI6MCwiU2NhbGUiOjIsIlNjYWxlRGVjaW1hbHMiOjIsIlNjYWxlU2VwYXJhdG9yIjowLCJTY2FsZUN1dG9mZiI6OTk5OTk5LCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIlBQRGlzcGxheVRpbWUiOjAsIkJ1aWxkQ29sb3VyIjoxLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIlBQRXhjbHVkZVRvcCI6MCwiUFBSaWdpZGVsTW9kZSI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiQ29sb3VyQmx1ZSI6IiM0YmI4ZjAiLCJDb2xvdXJHcmVlbiI6IiMwMGZmMDAiLCJDb2xvdXJZZWxsb3ciOiIjZmZmZjAwIiwiQ29sb3VyT3JhbmdlIjoiI2ZmN2YwMCIsIkNvbG91clJlZCI6IiNmZjAwMDAiLCJDb2xvdXJQdXJwbGUiOiIjZmYwMGZmIiwiQ29sb3VyR3JheSI6IiNiM2IzYjMiLCJDb2xvdXJQaW5rIjoiI2ZmMTQ5MyIsIkNvbG91ckJyb3duIjoiIzhiNDUxMyIsIkJvdEJhciI6MSwiVGltZXJCYXIiOjEsIlRpbWVyQmFyUG9zIjowLCJUaW1lckJhck92ZXJsYXkiOjIsIkF1dG9zYXZlVGltZXJCYXIiOjAsIlVwQmFyQ29sb3VyIjoxLCJVcGdyYWRlQmFyRml4ZWRQb3MiOjEsIlNvcnRCdWlsZGluZ3MiOjAsIlNvcnRVcGdyYWRlcyI6MCwiVXBncmFkZXNOZXZlckNvbGxhcHNlIjowLCJEcmFnb25BdXJhSW5mbyI6MSwiR3JpbW9pcmVCYXIiOjEsIkdDVGltZXIiOjEsIkZhdmljb24iOjEsIldyaW5rbGVyQnV0dG9ucyI6MSwiSGlkZVNlY3Rpb25zQnV0dG9ucyI6MCwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjEsIlRvb2xXYXJuTHVja3lGcmVuenkiOjEsIlRvb2xXYXJuQ29uanVyZSI6MSwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjoxLCJUb29sV2FybkVkaWZpY2UiOjEsIlRvb2xXYXJuVXNlciI6MCwiVG9vbFdhcm5Cb24iOjEsIlRvb2xXYXJuUG9zIjoxLCJUb29sdGlwR3JpbSI6MSwiVG9vbHRpcFdyaW5rIjoxLCJUb29sdGlwTHVtcCI6MSwiVG9vbHRpcFBsb3RzIjoxLCJUb29sdGlwUGFudGhlb24iOjEsIlRvb2x0aXBBc2NlbmRCdXR0b24iOjEsIlN0YXRzIjoxLCJNaXNzaW5nVXBncmFkZXMiOjEsIk1pc3NpbmdBY2hpZXZlbWVudHMiOjAsIlVwU3RhdHMiOjEsIkhlYXZlbmx5Q2hpcHNUYXJnZXQiOjEsIlNob3dNaXNzZWRHQyI6MSwiVGl0bGUiOjEsIkdlbmVyYWxTb3VuZCI6MSwiR0NOb3RpZmljYXRpb24iOjAsIkdDRmxhc2giOjEsIkNvbG91ckdDRmxhc2giOiIjZmZmZmZmIiwiR0NTb3VuZCI6MSwiR0NWb2x1bWUiOjEwMCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjowLCJGb3J0dW5lRmxhc2giOjEsIkNvbG91ckZvcnR1bmVGbGFzaCI6IiNmZmZmZmYiLCJGb3J0dW5lU291bmQiOjEsIkZvcnR1bmVWb2x1bWUiOjEwMCwiRm9ydHVuZVNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTc0LzE3NDAyN18zMjQyNDk0LWxxLm1wMyIsIlNlYU5vdGlmaWNhdGlvbiI6MCwiU2VhRmxhc2giOjEsIkNvbG91clNlYUZsYXNoIjoiI2ZmZmZmZiIsIlNlYVNvdW5kIjoxLCJTZWFWb2x1bWUiOjEwMCwiU2VhU291bmRVUkwiOiJodHRwczovL3d3dy5mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTIxLzEyMTA5OV8yMTkzMjY2LWxxLm1wMyIsIkdhcmRGbGFzaCI6MSwiQ29sb3VyR2FyZEZsYXNoIjoiI2ZmZmZmZiIsIkdhcmRTb3VuZCI6MSwiR2FyZFZvbHVtZSI6MTAwLCJHYXJkU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMDMvMTAzMDQ2Xzg2MTcxNC1scS5tcDMiLCJNYWdpY05vdGlmaWNhdGlvbiI6MCwiTWFnaWNGbGFzaCI6MSwiQ29sb3VyTWFnaWNGbGFzaCI6IiNmZmZmZmYiLCJNYWdpY1NvdW5kIjoxLCJNYWdpY1ZvbHVtZSI6MTAwLCJNYWdpY1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMjIxLzIyMTY4M18xMDE1MjQwLWxxLm1wMyIsIldyaW5rbGVyTm90aWZpY2F0aW9uIjowLCJXcmlua2xlckZsYXNoIjoxLCJDb2xvdXJXcmlua2xlckZsYXNoIjoiI2ZmZmZmZiIsIldyaW5rbGVyU291bmQiOjEsIldyaW5rbGVyVm9sdW1lIjoxMDAsIldyaW5rbGVyU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjQvMTI0MTg2XzgwNDMtbHEubXAzIiwiV3JpbmtsZXJNYXhOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyTWF4Rmxhc2giOjEsIkNvbG91cldyaW5rbGVyTWF4Rmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJNYXhTb3VuZCI6MSwiV3JpbmtsZXJNYXhWb2x1bWUiOjEwMCwiV3JpbmtsZXJNYXhTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE1Mi8xNTI3NDNfMTU2NjMtbHEubXAzIiwiQnVsa0J1eUJsb2NrIjoxLCJGYXZvdXJpdGVTZXR0aW5ncyI6MX0sImhlYWRlcnMiOnsiRmF2b3VyaXRlIjoxLCJDYWxjdWxhdGlvbiI6MSwiTm90YXRpb24iOjEsIkNvbG91cnMiOjEsIkJhcnNEaXNwbGF5IjoxLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjoxLCJOb3RpZmljYXRpb24iOjEsIk5vdGlmaWNhdGlvbkdlbmVyYWwiOjEsIk5vdGlmaWNhdGlvbkdDIjoxLCJOb3RpZmljYXRpb25GQyI6MSwiTm90aWZpY2F0aW9uU2VhIjoxLCJOb3RpZmljYXRpb25HYXJkIjoxLCJOb3RpZmljYXRpb25NYWdpIjoxLCJOb3RpZmljYXRpb25XcmluayI6MSwiTm90aWZpY2F0aW9uV3JpbmtNYXgiOjEsIk1pc2NlbGxhbmVvdXMiOjEsIkx1Y2t5IjoxLCJDaGFpbiI6MSwiU3BlbGxzIjoxLCJHYXJkZW4iOjEsIlByZXN0aWdlIjoxLCJXcmluayI6MSwiU2VhIjoxLCJBY2hpZXZzIjoxLCJNaXNjIjoxLCJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjF9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W10sImxvY2tlZE1pbmlnYW1lcyI6W10sInZlcnNpb24iOiIyLjAzMS4xMCJ9O2Nvb2tpZU1vbnN0ZXJGcmFtZXdvcms6eyJzZXR0aW5ncyI6e30sImhlYWRlcnMiOnsiaW5mb01lbnUiOjEsIm9wdGlvbnNNZW51IjoxfSwiZmF2b3VyaXRlU2V0dGluZ3MiOltdfTs%3D%21END%21`

**Comment by ChallengerCode** [comment]
And no, no mods and without any browser script or extension.

**Comment by DanielNoord** [comment]
No luck yet.. Both in Safari and Brave I can't reproduce.
Tested both the Stats and Options page while clicking and without clicking and both remained at the same position.
Is there any console output?

Note that the save-file you shared does include mod save data. This is due to how CC "wipes" your save data: it does not remove mod data. So when when loading save A with mod data, wiping and sharing save B you will actually include mod data from save A. Not much we can do about that sadly..

**Comment by ChallengerCode** [comment]
No console output other than the two mod added lines.

This issue seems to only happen with a large enough window, maximized on my 2560x1440 screen and as a window starting with size > 2000x1300. No idea how that's possible.

**Comment by DanielNoord** [comment]
I can indeed reproduce when forcing chrome to load on a bigger screen.

I have one possible idea about what is happening: 
2.031.10 uses an event listener to inject the code for the options section into the menu. The listener is called every time the `menu`-div is updated. Previously we just added it at runtime by injecting code into the `drawMenu` function.
What I think might be happening is that because of the listener the `menu`-div is initially drawn without the CM-options added, which make the page scroll up as it no longer covers the length of the screen. Then the CM-options are added but previous location is now forgotten.

**Comment by ChallengerCode** [comment]
Glad you managed to track it down, thanks for looking into it! :-)
My only idea so far would be bloating the initial menu div size as a hacky fix, not very elegant though.

Luckily it isn't a big issue as long as I can set the options with a smaller window it's fine!

**Comment by mostly-nonsense** [comment]
I can second this scrolling to top behaviour - firefox maximised window.  Left mouse hold on scroll bar holds in place while looking for an option, but there is at best a few seconds to make your selection.  A little larger than a small annoyance.

**Comment by RexTheCapt** [comment]
Can reproduce on 3 different monitors and 2 different computers (1 laptop, 1 custom desktop).

**Comment by Dantasstic** [comment]
Can confirm this happens to me as well on Firefox 91, very annoying

**Comment by worldendDominator** [comment]
Same happening here. I have two questions:
1) What changed to make this happen? I think it started a few days or weeks ago (not sure though).
2) Is it possible to move mod settings to a separate menu? That would fix the problem.

**Comment by micaminoff** [comment]
Confirmed happening on latest ff. Every 5 seconds. I added a DOM mutation break. Here's some stuff that might help you debug.

Break condition:
```
Paused on DOM mutation
DOM Mutation: 'subtreeModified'
div#menu
Added:div.close.menuClose
```

Call stack (top 6 rows)
```
UpdateMenu (https://orteil.dashnet.org/cookieclicker/main.js?v=2.090#6097)
UpdateMenu (https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js#2)
Logic (https://orteil.dashnet.org/cookieclicker/main.js?v=2.090#14229)
Logic (https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js#2)
Loop (https://orteil.dashnet.org/cookieclicker/main.js?v=2.090#14395)
Loop (https://orteil.dashnet.org/cookieclicker/main.js?v=2.090#14458)
... more Loop (...2.090#14458) calls
```

main.js break point at `main.js#6097`
`l('menu').innerHTML=str;`

CookieMonster.js break point at `CookieMonster.js#2:165858`
`(Z.UpdateMenu(),function(){const e=document.createElement("div");`

**Comment by DanielNoord** [comment]
Sorry for taking so long to respond. Other projects/tasks kept me occupied.
For anybody affected by this bug: 2.031.9 should work fine while this bug is still around.

@micaminoff 
https://github.com/CookieMonsterTeam/CookieMonster/blob/f4445f7b0a5dbaace0b70227b025e8b97392f860/src/Main/Initialization.js#L31-L33
This registers two functions to a "listener array" which create "menu objects" using functions from the CM Framework.

https://github.com/CookieMonsterTeam/CookieMonsterFramework/tree/main/src/frameworkDataObject/menuSections/addMenu.js#L8-L24
This function responds to the `EventListener` and calls the functions stored in the listener arrays with `addInfoMenuSection` and `addOptionsMenuSection`.

https://github.com/CookieMonsterTeam/CookieMonsterFramework/tree/main/src/frameworkDataObject/init.js#L16-L22
This is the initial creation of the listener, which gets replaced after each call to it.

I started using the listener because I wanted to avoid all the code insertion which makes CM incompatible with other mods and vice-versa. Without a proper modding api modders need to inject code one way or another and I hoped listeners would allow us to do so without interfering with code from other mods. However, it seems this create unforeseen issues. I have not come up with a good solution until now, but I am open to all suggestions.

**Comment by micaminoff** [comment]
No idea what could be causing it. But here are some observations about screen size.
* Scrolling happens when using "responsive design mode" to force small screen size through devtools (ff and chrome)
* Scrolling to top doesn't happen on an actual mobile device (at least chrome on android)
* Scrolling stutters on mobile if the menu is refreshed while scrolling
* Scrolling happens even if we collapse the Cookie Monster Mod Family Section and scroll down a bit. Basically whenever there's overflow.

My initial though was that maybe the node is deleted for a single frame to be updated, but it seems to be replaced in-place. It also doesn't happen in the Info pane which is weird. I also found no code relating to `scroll` or `offset` in either Cookie Monster or Cookie Clicker source.

I agree it would be good to find the cause and I really can't think of a good workaround for now.

**Comment by RexTheCapt** [comment]
How do we change witch version to use?

**Comment by micaminoff** [comment]
@RexTheCapt 

No easy way that I can find. You can checkout the tag that works and load it manually.

**Comment by jlandrum** [comment]
Setting the `#menu` height prevents the effect. I set it to `6000px` which if I scroll to the VERY bottom it jolts up slightly on update.

Not ideal but in my experience with rehydrating scroll state, it's a lot safer.

**Comment by jlandrum** [comment]
A possible solution - a div can be added before `#menu` (or after with `pointer-events: none` that when the menu renders, copies the height of `#menu` and updates on item expand/collapse. This would be pretty compatible with any other plugins that also inject or otherwise modify `#menu` as the issue seems to be because there are two layout invocations, one when the vanilla menu is reloaded and one when the Cookie Monster menu is added.

There also could be an optimization to how the menu is populated as it does appear to create new nodes every time the menu updates, even if there are no changes.

**Comment by jlandrum** [comment]
> How do we change witch version to use?
> […](#)

```
javascript: (function () {
  Game.LoadMod('https://github.com/CookieMonsterTeam/CookieMonster/blob/2.031.9/dist/CookieMonster.js');
}());
```

Replace `2.031.9` with the tag you wish to use.

**Comment by RexTheCapt** [comment]
Didn’t work. Tried using the top 5 tags in releases. If I did not use the default string to load the mod I kept getting cookie rejected in the console. I have even tried clearing all site data between tries too. From: James LandrumSent: søndag 22. august 2021 06:01To: CookieMonsterTeam/CookieMonsterCc: RexTheCapt; MentionSubject: Re: [CookieMonsterTeam/CookieMonster] Options page keeps scrolling back to the top (#918) How do we change witch version to use?…javascript: (function () {   Game.LoadMod('https://github.com/CookieMonsterTeam/CookieMonster/blob/2.031.9/dist/CookieMonster.js'); }()); Replace 2.031.9 with the tag you wish to use.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DanielNoord** [comment]
You could paste all text found on [https://raw.githubusercontent.com/CookieMonsterTeam/CookieMonster/2.031.9/dist/CookieMonster.js](https://raw.githubusercontent.com/CookieMonsterTeam/CookieMonster/2.031.9/dist/CookieMonster.js) (or any other tag) and paste it into your browser console.

**Comment by DanielNoord** [comment]
> A possible solution - a div can be added before `#menu` (or after with `pointer-events: none` that when the menu renders, copies the height of `#menu` and updates on item expand/collapse. This would be pretty compatible with any other plugins that also inject or otherwise modify `#menu` as the issue seems to be because there are two layout invocations, one when the vanilla menu is reloaded and one when the Cookie Monster menu is added.

The problem is that I most other mods inject into the "vanilla menu reload", which is also what CM did previously. However, this can create issues of mods being incompatible. Which is what the new reloading mechanism aims to solve.

> There also could be an optimization to how the menu is populated as it does appear to create new nodes every time the menu updates, even if there are no changes.

Good point.


In any case, finding why this only happens on larger windows might give us a better angle at finding a solution. I don't have much time myself for this and would be willing to merge a quick hot fix in the meantime if anybody finds something (such as setting the height).
Does the issue persist if you make the browser window smaller?

**Comment by jlandrum** [comment]
I don’t think it would be too incompatible - all it will effectively do is create a block element that maintains size (and can re-measure every time the hook is called) - so any mods that modify the content either using hooks or overrides will adjust the size and it will update the placeholder accordingly.

In my testing it appears to be a race condition, but it always happens on WebKit based browsers - the issue is the vanilla menu is loaded into DOM, a layout is invoked, causing any scrollable views to adjust their scroll offset to content height minus element height if below current, then the hook invokes adding to #menu again. While it happens fast enough that flickering doesn’t occur - most likely due to a render call being delayed as they are queued and possibly using vsync. Given that it appears for me on every instance of Safari I’ve tried at any, either WebKit does not use a queue for layout, or it’s layout code is too fast that even if it’s queued it completes by the time the hook modifies the DOM. 

I’m a bit overwhelmed from this week but if nobody manages a solution I could try playing around with the idea and if I make something work I can create a PR - do you have any suggestions for mods that would be best to test along side that modify the render method?

**Comment by DanielNoord** [comment]
The main problem is injecting it into the game's draw function.
What most mods do is something like this:
```javascript
Game.UpdateMenuBackUp = Game.UpdateMenu
Game.UpdateMenu = function() {
 Game.UpdateMenuBackUp()
 ModMenuFunction()
}
```
This becomes problematic when different mods want to add to `Game.UpdateMenu`, especially when they want to pass variables to `ModMenuFunction`. I hoped that event listeners might help avoid this clunky way of injecting code into the game's code, but it seems that is problematic.
I don't know if there is a way to set the height of #menu without injecting like in the example.

**Comment by SirFireball3521** [comment]
I'm a bit late to this discussion, but I'm also having this issue and thought of a slightly hacky solution for it. You could try storing the user's scroll position, and then running ``Element.scrollTo()`` after it reloads.

**Comment by DanielNoord** [comment]
This should now be fixed! Let me know if there are any remaining problems!

**Comment by ChallengerCode** [comment]
Works great, thank you! :-)
