### ISSUE TITLE
[Steam Version] This mod disable the Steam's keybinds

### ISSUE THREAD

**Issue by AFKoncore** [CookieMonsterTeam/CookieMonster#951]
**Describe the bug**
When using this mod on the steam version keybinds such as F12 (take a screenshot) and Shift+TAB (open the Steam overlay) are not working anymore.

**Browser**
Steam Version (Electron)

**Comment by witcheslive** [comment]
@Pyrite19 what are you talking about? the mod mostly works with the steam version of cookie clicker, which is a real thing that actually exists, but it has a couple of issues but overall otherwise works, and the author of this mod has expressed interest in a steam workshop version but you can load it by creating a couple of text files yourself. don't be a wet blanket, if you're dealing with cookies a dry blanket is much preferred

**Comment by DanielNoord** [comment]
I currently don't have the Steam version myself so I can't really investigate this. Do you have this issue with other games/mods?

**Comment by RandomGuyJCI** [comment]
Steam keybinds seem to be working for me, maybe it has been fixed in a recent commit?

**Comment by DanielNoord** [comment]
The recent commit did not do anything specifically with keybinds. Can other uses report whether they are experiencing issues?

**Comment by pie3636** [comment]
I had the same issue but it also became fixed for me within the last ~18 hours.

**Comment by DanielNoord** [comment]
If somebody else also reports that this is now fine I am going to close this!

**Comment by Pyrite19** [comment]
Works fine now

**Comment by DanielNoord** [comment]
Closing this then! Thanks for all the reports!
